---
dist: trusty
sudo: required
language: python

services:
  - mysql

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-pip -qq

  # Install systemd required for the service file
  - sudo apt-get install systemd -qq

install:
  # Install Ansible
  - pip install ansible

script:
  # Basic role syntax check
  - ansible-playbook tests/role.yml --syntax-check

  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i "localhost," tests/role.yml --connection="local" --become --extra-vars="@tests/travis_extra_vars.json"

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i "localhost," tests/role.yml --connection=local --become --extra-vars="@tests/travis_extra_vars.json"
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
